### ISSUE TITLE
Support HTML suffix

### ISSUE THREAD

**Issue by joaocunha** [FGRibreau/node-truncate#4]
It would be great to be able to append some HTML after the ellipsis. In this example, there's a link to continue reading.

![image](https://cloud.githubusercontent.com/assets/766837/10984658/01ad4f12-8402-11e5-9584-25f0db431ddb.png)

**Comment by FGRibreau** [comment]
You already can :)

``` js
truncate("1234 http://google.com hey :)", 4, {ellipsis:'<a>continue reading</a>'}); 
```

**Comment by joaocunha** [comment]
:100:!
